FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ARG API_URL
ENV API_URL=${API_URL}
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/public /usr/share/nginx/html
COPY nginx.production.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
